### ISSUE TITLE
dash pattern and dash phase, real numbers?

### ISSUE THREAD

**Issue by domfe** [libharu/libharu#20]
Hi.
I think the function HPDF_Page_SetDash is wrong. In PDF documents, the elements of the dash pattern array can be real numbers.
The dash phase can be a real number also. Maybe the libharu function must be changed to operate correctly.

Regards,
Dome

**Comment by karstenBriksoft** [comment]
This fix breaks compatibility with code that still thinks that the `HPDF_Page_SetDash` function expects INT parameters. If you're compiling everything in `C` you're probably fine and the compiler will tell you to fix the parameters, but if you don't then you pass integers where floats are expected and then the code raises an error because the parameters are out of range.
It would have been a lot better to introduce something like a new `HPDF_Page_SetDashReal` function. The original function may even be a simple wrapper function around the new function. 

Without it version 2.4 is actually incompatible with previous versions.
